//Exception in js
//try , catch finally throw
// try{
//     console.log(tullu)
// }catch(err){
//     console.log(err);
// }

try{
    setTimeout(()=>{
    console.log(tullu);
},10000)
}catch(err){
   console.log(err)
}

 setTimeout(()=>{
console.log("hacking facebook....please wait........");
 },1000
 )
 setTimeout(()=>{
    console.log("password...username..........");
    document
    // console.log(tullu); //ReferenceError: tullu is not defined remaing code Execution was stopped
 },2000
 )
 setTimeout(()=>{
    console.log("**BOOM**BOOM**........facebook hacked...............BOOM***BOOM**");
 },4000
 )
